openapi: 3.0.0
info:
  title: CRM API
  version: 1.0.0
  description: API para gestionar compañías, leads, plantillas y contactos
servers:
  - url: http://localhost:3000
paths:
  /companies:
    get:
      summary: Obtener todas las compañías
      responses:
        '200':
          description: Lista de compañías 