swagger: "2.0"
info:
  description: "API Documentation"
  version: "1.0.0"
  title: "Kuali API"
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"
paths:
  /companies:
    get:
      tags:
        - "Companies"
      summary: "Obtener listado de empresas"
      responses:
        200:
          description: "Lista de empresas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Company"
    post:
      tags:
        - "Companies"
      summary: "Crear una empresa"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la empresa a crear"
          required: true
          schema:
            $ref: "#/definitions/CompanyInput"
      responses:
        201:
          description: "Empresa creada"
          schema:
            $ref: "#/definitions/Company"
  /leads:
    get:
      tags:
        - "Leads"
      summary: "Obtener listado de leads"
      responses:
        200:
          description: "Lista de leads"
          schema:
            type: array
            items:
              $ref: "#/definitions/Lead"
    post:
      tags:
        - "Leads"
      summary: "Crear un nuevo lead"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del lead a crear"
          required: true
          schema:
            $ref: "#/definitions/LeadInput"
      responses:
        201:
          description: "Lead creado"
          schema:
            $ref: "#/definitions/Lead"
  /templates:
    get:
      tags:
        - "Templates"
      summary: "Obtener todas las plantillas"
      responses:
        200:
          description: "Lista de plantillas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Template"
    post:
      tags:
        - "Templates"
      summary: "Crear una plantilla"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la plantilla"
          required: true
          schema:
            $ref: "#/definitions/TemplateInput"
      responses:
        201:
          description: "Plantilla creada"
          schema:
            $ref: "#/definitions/Template"
  /contact-logs:
    get:
      tags:
        - "Contact_Logs"
      summary: "Obtener listado de registros de contacto"
      responses:
        200:
          description: "Lista de registros de contacto"
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact_Log"
    post:
      tags:
        - "Contact_Logs"
      summary: "Crear un registro de contacto"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del contacto"
          required: true
          schema:
            $ref: "#/definitions/Contact_LogInput"
      responses:
        201:
          description: "Contacto creado"
          schema:
            $ref: "#/definitions/Contact_Log"
definitions:
  Company:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      sector:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
  CompanyInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      sector:
        type: string
  Lead:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      linkedinUrl:
        type: string
      role:
        type: string
      seniority:
        type: string
      status:
        $ref: "#/definitions/LeadStatus"
      companyId:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
  LeadInput:
    type: object
    required:
      - firstName
      - lastName
      - email
      - companyId
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      linkedinUrl:
        type: string
      role:
        type: string
      seniority:
        type: string
      companyId:
        type: string
  Template:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      body:
        type: string
      steps:
        type: object
        description: "Array de objetos con step, salesperson_response, client_response"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  TemplateInput:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
      steps:
        type: object
        description: "Array de objetos con step, salesperson_response, client_response"
  Contact_Log:
    type: object
    properties:
      id:
        type: string
      leadId:
        type: string
      templateId:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  Contact_LogInput:
    type: object
    required:
      - leadId
      - templateId
    properties:
      leadId:
        type: string
      templateId:
        type: string
  LeadStatus:
    type: string
    enum:
      - NUEVO
      - CONTACTADO
      - INTERESADO
      - CALIFICADO
      - OPORTUNIDAD
      - CERRADO
      - DESCARTADO
  ContactStatus:
    type: string
    enum:
      - PENDIENTE
      - ENVIADO
      - ENTREGADO
      - LEIDO
      - RESPONDIDO
      - FALLIDO 