swagger: "2.0"
info:
  description: "API Documentation"
  version: "1.0.0"
  title: "Kuali API"
host: "kuali-new-backend.onrender.com"
basePath: "/"
schemes:
  - "https"
paths:
  /companies:
    get:
      tags:
        - "Companies"
      summary: "Obtener listado de empresas"
      responses:
        200:
          description: "Lista de empresas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Company"
    post:
      tags:
        - "Companies"
      summary: "Crear una empresa"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la empresa a crear"
          required: true
          schema:
            $ref: "#/definitions/CompanyInput"
      responses:
        201:
          description: "Empresa creada"
          schema:
            $ref: "#/definitions/Company"
  /leads:
    get:
      tags:
        - "Leads"
      summary: "Obtener listado de leads"
      responses:
        200:
          description: "Lista de leads"
          schema:
            type: array
            items:
              $ref: "#/definitions/Lead"
    post:
      tags:
        - "Leads"
      summary: "Crear un nuevo lead"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del lead a crear"
          required: true
          schema:
            $ref: "#/definitions/LeadInput"
      responses:
        201:
          description: "Lead creado"
          schema:
            $ref: "#/definitions/Lead"
  /templates:
    get:
      tags:
        - "Templates"
      summary: "Obtener todas las plantillas"
      responses:
        200:
          description: "Lista de plantillas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Template"
    post:
      tags:
        - "Templates"
      summary: "Crear una plantilla"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la plantilla"
          required: true
          schema:
            $ref: "#/definitions/TemplateInput"
      responses:
        201:
          description: "Plantilla creada"
          schema:
            $ref: "#/definitions/Template"
  /templates/{id}:
    get:
      tags:
        - "Templates"
      summary: "Obtener una plantilla por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la plantilla"
      responses:
        200:
          description: "Plantilla encontrada"
          schema:
            $ref: "#/definitions/Template"
        404:
          description: "Plantilla no encontrada"
    put:
      tags:
        - "Templates"
      summary: "Actualizar una plantilla"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la plantilla"
        - in: "body"
          name: "body"
          description: "Datos a actualizar de la plantilla"
          required: true
          schema:
            $ref: "#/definitions/TemplateInput"
      responses:
        200:
          description: "Plantilla actualizada"
          schema:
            $ref: "#/definitions/Template"
        404:
          description: "Plantilla no encontrada"
    delete:
      tags:
        - "Templates"
      summary: "Eliminar una plantilla"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la plantilla"
      responses:
        204:
          description: "Plantilla eliminada"
        404:
          description: "Plantilla no encontrada"
  /templates/{id}/steps:
    get:
      tags:
        - "Templates"
      summary: "Obtener los steps de una plantilla"
      description: "Obtiene los pasos de una plantilla específica. Los pasos son validados para asegurar que tengan la estructura correcta."
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la plantilla"
      responses:
        200:
          description: "Steps de la plantilla"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Step"
        404:
          description: "Plantilla no encontrada o sin pasos definidos"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Steps no encontrados"
              message:
                type: "string"
                example: "La plantilla 'CV Scanner' no tiene pasos definidos"
        400:
          description: "Formato de steps inválido"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Formato de steps inválido"
              message:
                type: "string"
                example: "Uno o más steps no tienen la estructura correcta"
        500:
          description: "Error del servidor"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Error al obtener los steps de la plantilla"
              details:
                type: "string"
              stack:
                type: "string"
                description: "Solo disponible en ambiente de desarrollo"
    put:
      tags:
        - "Templates"
      summary: "Actualizar los steps de una plantilla"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la plantilla"
        - in: "body"
          name: "body"
          description: "Nuevos steps de la plantilla"
          required: true
          schema:
            type: "object"
            required:
              - "steps"
            properties:
              steps:
                type: "array"
                items:
                  $ref: "#/definitions/Step"
      responses:
        200:
          description: "Steps actualizados"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Step"
        404:
          description: "Plantilla no encontrada"
        400:
          description: "Formato de steps inválido"
  /contact-logs:
    get:
      tags:
        - "Contact_Logs"
      summary: "Obtener listado de registros de contacto"
      responses:
        200:
          description: "Lista de registros de contacto"
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact_Log"
    post:
      tags:
        - "Contact_Logs"
      summary: "Crear un registro de contacto"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del contacto"
          required: true
          schema:
            $ref: "#/definitions/Contact_LogInput"
      responses:
        201:
          description: "Contacto creado"
          schema:
            $ref: "#/definitions/Contact_Log"
  /interactions:
    get:
      tags:
        - "Interactions"
      summary: "Obtener listado de interacciones"
      responses:
        200:
          description: "Lista de interacciones"
          schema:
            type: array
            items:
              $ref: "#/definitions/Interaction"
    post:
      tags:
        - "Interactions"
      summary: "Crear una nueva interacción"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la interacción"
          required: true
          schema:
            $ref: "#/definitions/InteractionInput"
      responses:
        201:
          description: "Interacción creada"
          schema:
            $ref: "#/definitions/Interaction"
  /interactions/{id}:
    get:
      tags:
        - "Interactions"
      summary: "Obtener una interacción por ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la interacción"
      responses:
        200:
          description: "Interacción encontrada"
          schema:
            $ref: "#/definitions/Interaction"
        404:
          description: "Interacción no encontrada"
    put:
      tags:
        - "Interactions"
      summary: "Actualizar una interacción"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la interacción"
        - in: "body"
          name: "body"
          description: "Datos a actualizar de la interacción"
          required: true
          schema:
            $ref: "#/definitions/InteractionInput"
      responses:
        200:
          description: "Interacción actualizada"
          schema:
            $ref: "#/definitions/Interaction"
        404:
          description: "Interacción no encontrada"
    delete:
      tags:
        - "Interactions"
      summary: "Eliminar una interacción"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          description: "ID de la interacción"
      responses:
        204:
          description: "Interacción eliminada"
        404:
          description: "Interacción no encontrada"
  /leads/{leadId}/interactions:
    get:
      tags:
        - "Interactions"
      summary: "Obtener interacciones de un lead específico"
      parameters:
        - name: "leadId"
          in: "path"
          required: true
          type: "string"
          description: "ID del lead"
      responses:
        200:
          description: "Lista de interacciones del lead"
          schema:
            type: array
            items:
              $ref: "#/definitions/Interaction"
        404:
          description: "Lead no encontrado"
definitions:
  Company:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      sector:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
  CompanyInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      sector:
        type: string
  Lead:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      # Campos de empresa
      companyName:
        type: string
      industry:
        type: string
      companySize:
        type: string
        description: "Tamaño de la empresa (e.g., '1-10', '11-50', '51-200')"
      annualRevenue:
        type: number
        format: decimal
        description: "Ingresos anuales estimados"
      # Campos de seguimiento
      status:
        $ref: "#/definitions/LeadStatus"
      leadSource:
        type: string
        description: "Origen del lead (e.g., 'website', 'referral', 'campaign')"
      lastContactAt:
        type: string
        format: date-time
      leadScore:
        type: integer
        description: "Puntuación del lead (0-100)"
      # Campos de marketing
      campaignId:
        type: string
      utmSource:
        type: string
      utmMedium:
        type: string
      utmCampaign:
        type: string
      acquisitionCost:
        type: number
        format: decimal
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
  LeadInput:
    type: object
    required:
      - firstName
      - lastName
      - email
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      companyName:
        type: string
      industry:
        type: string
      companySize:
        type: string
      annualRevenue:
        type: number
      leadSource:
        type: string
      leadScore:
        type: integer
      campaignId:
        type: string
      utmSource:
        type: string
      utmMedium:
        type: string
      utmCampaign:
        type: string
      acquisitionCost:
        type: number
  Template:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      body:
        type: string
      steps:
        type: array
        items:
          $ref: "#/definitions/Step"
      tags:
        type: array
        items:
          type: string
        description: "Etiquetas para categorizar y organizar templates"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  TemplateInput:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
      steps:
        type: array
        items:
          $ref: "#/definitions/Step"
      tags:
        type: array
        items:
          type: string
        description: "Etiquetas para categorizar y organizar templates"
  Contact_Log:
    type: object
    properties:
      id:
        type: string
      leadId:
        type: string
      templateId:
        type: string
      status:
        $ref: "#/definitions/ContactStatus"
        description: "Estado actual del contacto"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  Contact_LogInput:
    type: object
    required:
      - leadId
      - templateId
    properties:
      leadId:
        type: string
      templateId:
        type: string
      status:
        $ref: "#/definitions/ContactStatus"
        description: "Estado inicial del contacto"
  LeadStatus:
    type: string
    enum:
      - NEW
      - CONTACTED
      - QUALIFIED
      - OPPORTUNITY
      - CUSTOMER
      - LOST
  ContactStatus:
    type: string
    enum:
      - PENDIENTE
      - ENVIADO
      - ENTREGADO
      - LEIDO
      - RESPONDIDO
      - FALLIDO
  Step:
    type: object
    required:
      - step
      - salesperson_response
      - client_response
    properties:
      step:
        type: string
        description: "Nombre o número del paso (ej: '1 Presentación', 'Diagnóstico')"
        example: "1 Presentación"
      salesperson_response:
        type: string
        description: "Script o respuesta del vendedor. Puede incluir placeholders como <cliente> o <vendedor>"
        example: "¡Hola, <cliente>! Soy <vendedor>, de Kuali.ai."
      client_response:
        type: string
        description: "Respuesta esperada o ejemplo del cliente"
        example: "Hola, me interesa saber más."
  Interaction:
    type: object
    properties:
      id:
        type: string
      leadId:
        type: string
      type:
        $ref: "#/definitions/InteractionType"
      notes:
        type: string
      result:
        type: string
      scheduledAt:
        type: string
        format: date-time
      completedAt:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  InteractionInput:
    type: object
    required:
      - leadId
      - type
    properties:
      leadId:
        type: string
      type:
        $ref: "#/definitions/InteractionType"
      notes:
        type: string
      result:
        type: string
      scheduledAt:
        type: string
        format: date-time
  InteractionType:
    type: string
    enum:
      - CALL
      - EMAIL
      - MEETING
      - DEMO
      - OTHER 